name: Cypress Tests

on:
  push:

# Workflow - What and when should run
# Jobs - The individual activities
# Steps - The individual tasks within a job

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          overwrite: true
          path: cypress/screenshots
          if-no-files-found: ignore
